server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-boot-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot-app
          service_name: tel
          __path__: /var/log/app/*.log

    pipeline_stages:
      # Parse JSON logs
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            traceId: traceId
            spanId: spanId
            thread: thread

      # Extract labels
      - labels:
          level:
          traceId:
          spanId:
          service_name:

      # Set timestamp
      - timestamp:
          source: timestamp
          format: RFC3339

      # Output the message
      - output:
          source: message
