spring:
  application:
    name: service-e
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8085

# OpenTelemetry Configuration
management:
  # Tracing Configuration
  tracing:
    sampling:
      probability: 1.0

  # OTLP endpoint configuration
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces

  # Metrics Configuration
  metrics:
    export:
      # OTLP metrics export
      otlp:
        enabled: true
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics
        step: 10s

      # Prometheus metrics
      prometheus:
        enabled: true

    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

    # Enable JVM and system metrics
    enable:
      jvm: true
      process: true
      system: true

  # Actuator endpoints
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics

# Logging - include trace context in MDC
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
